apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  namespace: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app-container
          image: kunalch23/nodejs-helloworld:14
          ports:
            - containerPort: 3000

